### ISSUE TITLE
Change viewport rendering mode to material preview when mountpoint mode is turned on

### ISSUE THREAD

**Issue by TheWizardLizard** [enenra/space-engineers-utilities#171]
In the default viewport shading mode, mountpoint planes don't get their texture unless the viewport is in "Material Preview" shading mode.

![image](https://user-images.githubusercontent.com/17933206/75758183-a9013300-5d01-11ea-983b-5f06e2da5d60.png)

**Comment by enenra** [comment]
Okay, I've thought about this one a bit more and I'm not going to change this. The reason for that is that changing to shaded mode with materials causes materials to be loaded. And depending on the file and PC that can take a long time. The user will not be aware of this though so it might seem like Blender is crashing.

As a result I think this is better suited as a note in the documentation rather than a functionality of the addon itself.
