### ISSUE TITLE
Empty custom propery doesnt update properly when value changed in UI element.

### ISSUE THREAD

**Issue by cstahlhut** [enenra/space-engineers-utilities#182]
https://cdn.discordapp.com/attachments/161758345856811008/687084181628387332/unknown.png

https://cdn.discordapp.com/attachments/161758345856811008/687084287933153331/unknown.png

https://cdn.discordapp.com/attachments/161758345856811008/687084400785096762/unknown.png

https://cdn.discordapp.com/attachments/161758345856811008/687084698379485190/unknown.png

Basically I set it to seat then change the name due to needing _section_ in it, I updated the selected via the UI element, however the custom property did not update to reflect the change.

**Comment by enenra** [comment]
I just checked the code and this definitely should update. Is there a chance that you renamed the highlight object *after* assigning it to the highlight empty? Because we can't know when an arbitrary object gets updated unfortunately. What I can do though is update the custom property on export, so that should cover this case.
