### ISSUE TITLE
Export fail on export all scenes

### ISSUE THREAD

**Issue by TheWizardLizard** [enenra/space-engineers-utilities#200]
![image](https://user-images.githubusercontent.com/17933206/88456693-c61fd500-ce4d-11ea-9f5a-5a8e583d9953.png)

Fixed by selecting root object in all scenes then trying again

**Comment by enenra** [comment]
What did you have selected beforehand for it to fail? The error it's giving happens when it can't set the currently active screen area into object mode (need to do that for export). So in theory what is selected should not make a difference at all. Instead, what screen area is currently active makes a difference.

**Comment by TheWizardLizard** [comment]
Seems to be related to having a hidden object (such as a collision object) selected while trying to export
