### ISSUE TITLE
(Blender 4.2) Icon rendering not using alpha possible fix

### ISSUE THREAD

**Issue by stonelords** [enenra/space-engineers-utilities#404]
The icon render not using alpha so just a square of colour overlay around block.

Able to fix it by
1: enabling transparent in Render/EEVEE/Film/ ticked the box called transparent
2:  in the compositing tab i enabled use alpha in viewer

![blender fix](https://github.com/user-attachments/assets/238a94b7-6cf3-4fc2-b44d-d7aa5b6322f5)

**Comment by orangep9** [comment]
As I posted in discord a bit ago I had a similar but slightly different issue. When you render a icon in a scene that doesn't have a World it results in a black background instead of transparency. A common cause of that is rendering in a second scene that you added since it doesn't have a world be default.

Both issues seem like they could be fixed by checking render settings before starting the render.
