### ISSUE TITLE
overriding the icon path from default

### ISSUE THREAD

**Issue by Uncboog** [enenra/space-engineers-utilities#411]
just a wee request to have the icon path changed from its current "default" to the currently set mod folder in the export options section, thank you

**Comment by enenra** [comment]
The icon path could just be updated when an icon is rendered, should it still be the default. Way easier than trying to determine if a new icon has been rendered during export.

**Comment by enenra** [comment]
So this is actually already implemented, but because the SBC is only updated on export from Blender, you won't see the new path until you do that. 
It doesn't really make sense to change that as just updating the SBC without exporting is not intuitive - all other changes only happen on export too and there are people who prefer SEUT not to touch the SBCs at all.
